apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-deploy
  labels:
    name: redis-app-deploy
    app: demo-app-redis
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo-app-redis
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: demo-app-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379