apiVersion: v1 
kind: Service
metadata:
  name: redis
  labels:
    name: clusterip-app-service
    app: demo-app-redis
spec:
  type: ClusterIP
  selector:
      name: redis-pod
      app: demo-app-redis
  ports:
    - port: 6379
      targetPort: 6379