apiVersion: v1 
kind: Service
metadata:
  name: nodeport-service
  labels:
    name: nodeport-service
    app: demo-app-redis
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    name: webapp-pod
    app: demo-app-redis